# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  encoding: utf8
  database: lab_cmpe282
  username: ap_cmpe282
  password: ap_cmpe282
  host: cmpe282.c1jewuh8gp2c.us-west-2.rds.amazonaws.com
  port: 3306
  pool: 5

development:
  adapter: mysql
  encoding: utf8
  database: lab_cmpe282
  username: ap_cmpe282
  password: ap_cmpe282
  host: cmpe282.c1jewuh8gp2c.us-west-2.rds.amazonaws.com
  port: 3306
  pool: 5

test:
  adapter: mysql
  encoding: utf8
  database: lab_cmpe282
  username: ap_cmpe282
  password: ap_cmpe282
  host: cmpe282.c1jewuh8gp2c.us-west-2.rds.amazonaws.com
  port: 3306
  pool: 5

production:
  adapter: mysql
  encoding: utf8
  database: lab_cmpe282
  username: ap_cmpe282
  password: ap_cmpe282
  host: cmpe282.c1jewuh8gp2c.us-west-2.rds.amazonaws.com
  port: 3306
  pool: 5
